### ISSUE TITLE
Automatic attribution in generated map corner

### ISSUE THREAD

**Issue by cquest** [DantSu/php-osm-static-api#1]
OpenStreetMap based maps need attribution, see: https://openstreetmap.org/

It would be nice to add it automatically in the corner of the generated PNG.

Merci d'avance !

**Comment by DantSu** [comment]
Merci, je regarderai ça demain ;)

**Comment by DantSu** [comment]
Done !
How have you find this repo so quickly ?

**Comment by DantSu** [comment]
By the way, I have updating https://github.com/DantSu/php-french-cadastral-map-static-api too. Adding OpenStreetMap attribution if user display it in background ;)

**Comment by cquest** [comment]
Repo trouvé grâce à https://twitter.com/cq94/status/1435637540191670272

Merci pour les fix

**Comment by DantSu** [comment]
Ah oue ! Un bot tweeter qui référence tous les nouveaux packages composer ! Je connaissais pas ! Merci pour la réponse :)

**Comment by kasperkamperman** [comment]
I saw you made the getMapImage protected instead of public. This means all generate images have a hardcoded attribution. 

While I think it's a good default, you probably should allow getMapImage() as well. 

This is what I could found on attribution. 

> Static images
Static images must be generally attributed the same way as interactive maps. However, if multiple static images appear on the same document, one instance of attribution is sufficient. (For images where hyperlinking is not possible, see the “Books, magazines and printed maps” section.)

> In accordance with the Substantial Guideline, static images of fewer than 100 features do not require attribution. In addition, static images of areas less than 10,000 m2 do not require attribution. Small thumbnails/icons do not require attribution.

https://osmfoundation.org/wiki/Licence/Attribution_Guidelines#Static_images
